version: '3.8'

services:
  web:
    image: app-name:latest
    build:
      target: web
      context: .
    env_file:
      - .env
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
  
  db:
    platform: "linux/amd64"
    image: mysql:5.7
    env_file:
      - .env
    environment:
      DB_HOST: host.docker.internal
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: simple-login
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: